### ISSUE TITLE
latexcolors should be on CTAN

### ISSUE THREAD

**Issue by tcpluess** [Inventium/latexcolor.com#8]
There should be a package, like my `.sty` here

https://github.com/tcpluess/latexcolors

on CTAN. Is that possible?

**Comment by doolin** [comment]
sure, whatever, knock yourself out

**Comment by tcpluess** [comment]
Done ;-)
see
https://ctan.org/pkg/latexcolors
and
https://github.com/tcpluess/latexcolors
